Fix server token generation, format CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,6 +27,10 @@ jobs:
           # * NOTE: All steps need to be run in this block, otherwise, we are operating back on the mac host
           set -exo pipefail
           #
+          # This sometimes fails in the image, so let's do it again
+          ntpdate pool.ntp.org
+          #
+          ### Basic user setup ##############################################
           TEST_USER=tester
           TEST_USER_HOME="/opt/$TEST_USER"
           REPO_NAME=${GITHUB_WORKSPACE##*/}
@@ -38,17 +42,19 @@ jobs:
           #
           mkdir -p "$TEST_USER_HOME"
           pw adduser -n "$TEST_USER" -d "$TEST_USER_HOME" -c "Tester" -h -
-          chown -R "$TEST_USER":"$TEST_USER" "$TEST_USER_HOME" "/$WORKSPACE_PARENT"/
+          chown -R "$TEST_USER":"$TEST_USER" "$TEST_USER_HOME"
+          chown -R "$TEST_USER":"$TEST_USER" "/$WORKSPACE_PARENT"/
           whoami
 
-          #
+          ### Install rust stable from rustup  ##############################
           su "$TEST_USER" -c "/bin/sh -exo pipefail" <<"EOH"
           whoami
           echo $HOME
           fetch -o /tmp/rustup.sh https://sh.rustup.rs
-          sh /tmp/rustup.sh -y --profile=minimal
+          time sh /tmp/rustup.sh -y --profile=minimal
           . $HOME/.cargo/env
-          ## Info
+
+          ### Output some information about the environment  ################
           # environment
           echo "## environment"
           env | sort
@@ -57,21 +63,24 @@ jobs:
           cargo -V
           rustc -V
           pkg info
-          #
+
+          ### Build project and run unit tests ##############################
           cd "$WORKSPACE"
           FAULT=0
-          RUSTFLAGS="-C debuginfo=0" cargo build --features "${{ matrix.job.features }}" || FAULT=1
-          #cargo test --features "${{ matrix.job.features }}" || FAULT=1
+          RUSTFLAGS="-C debuginfo=0" time \
+            cargo build --features "${{ matrix.job.features }}" || FAULT=1
+          #time cargo test --features "${{ matrix.job.features }}" || FAULT=1
           if [ "$FAULT" -eq 0 ]; then
             # save build time by avoiding "cargo install"
-            cp -a target/debug/sccache target/debug/sccache-dist $HOME/.cargo/bin/.
+            cp -a target/debug/sccache target/debug/sccache-dist \
+              $HOME/.cargo/bin/.
           fi
           # Clean to avoid to rsync back the files
           cargo clean
           if [ $FAULT -ne 0 ]; then exit 1; fi
 
-          ### run actual tests
-          echo "Run sccache-dist tests"
+          ### Prepare sccache-dist tests ####################################
+          echo "Prepare sccache-dist tests"
 
           SECRET_KEY="$(sccache-dist auth generate-jwt-hs256-key)"
           CLIENT_AUTH_KEY="$(sccache-dist auth generate-jwt-hs256-key)"
@@ -88,7 +97,8 @@ jobs:
           EOF
 
           SERVER_TOKEN="$(sccache-dist auth generate-jwt-hs256-server-token \
-            --config=/tmp/scheduler.conf --secret-key="$SECRET_KEY" --server="127.0.0.1:10501")"
+            --config=/tmp/scheduler.conf --secret-key="$SECRET_KEY" \
+            --server="127.0.0.1:10501")"
 
           # Create server.conf
           cat >/tmp/server.conf <<EOF
@@ -103,6 +113,8 @@ jobs:
           EOF
 
           # create sccache client config
+          TC="$(rustup toolchain list | grep default | awk '{ print $1 }')"
+          RUSTC_PATH="$HOME/.rustup/toolchains/$TC/bin/rustc"
           mkdir -p "$HOME/.config/sccache"
           cat >"$HOME/.config/sccache/config" <<EOF
           [dist]
@@ -122,13 +134,14 @@ jobs:
 
           [[dist.toolchains]]
           type = "path_override"
-          compiler_executable = "$HOME/.rustup/toolchains/stable-x86_64-unknown-freebsd/bin/rustc"
+          compiler_executable = "$RUSTC_PATH"
           archive = "$HOME/.config/sccache/rust-toolchain.tgz"
-          archive_compiler_executable = "$HOME/.rustup/toolchains/stable-x86_64-unknown-freebsd/bin/rustc"
+          archive_compiler_executable = "$RUSTC_PATH"
           EOF
 
           echo "Creating toolchain tarballs"
-          gtar cvf - --files-from /dev/null | gzip -n >$HOME/.config/sccache/empty.tar.gz
+          gtar cvf - --files-from /dev/null | gzip -n \
+            >$HOME/.config/sccache/empty.tar.gz
           gtar cf - --sort=name --mtime='2022-06-28 17:35Z' $HOME/.rustup  | \
             gzip -n >$HOME/.config/sccache/rust-toolchain.tgz
 
@@ -140,22 +153,23 @@ jobs:
 
           whoami
 
-          #
-          ## Create ZFS pool and configure pot
+          ### Create ZFS pool and configure pot ##############################
           dd if=/dev/zero of=/zfs1 bs=1 count=1 seek=2G
           zdev=$(mdconfig -a -t vnode -S 4096 -f /zfs1)
           zpool create -f potpool "$zdev"
           sysrc -f /usr/local/etc/pot/pot.conf POT_ZFS_ROOT=potpool/pot
           sysrc -f /usr/local/etc/pot/pot.conf POT_EXTIF="$PUB_INTF"
           pot init
-          pot create -p sccache-template -N alias -i "lo0|127.0.0.2" -t single -b "$OS_VERSION"
+          time pot create -p sccache-template -N alias -i "lo0|127.0.0.2" \
+            -t single -b "$OS_VERSION"
           pot set-cmd -p sccache-template -c /usr/bin/true
           pot set-attr -p sccache-template -A no-rc-script -V YES
           pot snapshot -p sccache-template
 
           echo "Starting build-server (as root)"
-          SCCACHE_DIST_ERROR_LOG=/tmp/sccache_server_log.txt SCCACHE_DIST_LOG=debug \
-            RUST_LOG=info $TEST_USER_HOME/.cargo/bin/sccache-dist server --config /tmp/server.conf &
+          SCCACHE_DIST_LOG=debug RUST_LOG=info \
+            $TEST_USER_HOME/.cargo/bin/sccache-dist server \
+            --config /tmp/server.conf &
           BUILD_SERVER_PID=$!
 
           su "$TEST_USER" -c "/bin/sh -exo pipefail" <<"EOH"
@@ -177,22 +191,28 @@ jobs:
             done
           done
 
-          # create test project
+          ### Create test project to test sccache-dist with ##################
           cargo init buildtest
           cd buildtest
           echo 'chrono = "0.4"' >>Cargo.toml
-          export RUSTC_WRAPPER=sccache
+
+          ### Start sccache server ###########################################
           SCCACHE_ERROR_LOG=/tmp/sccache_log.txt SCCACHE_LOG=info \
             SCCACHE_NO_DAEMON=1 RUST_LOG=info sccache --start-server
           SERVER_PID=$!
           echo "SERVER PID IS: $SERVER_PID"
-          cargo build
+
+          ### First build with sccache-dist ##################################
+          RUSTC_WRAPPER=sccache time cargo build
           STATS="$(sccache -s)"
           echo "Statistics of first buildtest"
           echo "$STATS"
-          CACHE_HITS="$(echo "$STATS" | grep "Cache hits" | grep -v Rust | awk '{ print $3 }')"
-          FAILED_DIST="$(echo "$STATS" | grep "Failed distributed compilations" | awk '{ print $4 }')"
-          SUCCEEDED_DIST="$(echo "$STATS" | (grep -F "127.0.0.1:10501" || true) | awk '{ print $2 }')"
+          CACHE_HITS="$(echo "$STATS" \
+            | grep "Cache hits" | grep -v Rust | awk '{ print $3 }')"
+          FAILED_DIST="$(echo "$STATS" \
+            | grep "Failed distributed compilations" | awk '{ print $4 }')"
+          SUCCEEDED_DIST="$(echo "$STATS" \
+            | (grep -F "127.0.0.1:10501" || true) | awk '{ print $2 }')"
 
           if [ "$CACHE_HITS" -ne 0 ]; then
             2>&1 echo "Unexpected cache hits"
@@ -206,16 +226,20 @@ jobs:
             2>&1 echo "No distributed compilations succeeded"
             exit 1
           fi
-          sccache -z
 
+          ### Second build with sccache-dist #################################
+          sccache -z
           cargo clean
-          cargo build
+          RUSTC_WRAPPER=sccache time cargo build
           STATS="$(sccache -s)"
           echo "Statistics of second buildtest"
           echo "$STATS"
-          CACHE_HITS="$(echo "$STATS" | grep "Cache hits" | grep -v Rust | awk '{ print $3 }')"
-          FAILED_DIST="$(echo "$STATS" | grep "Failed distributed compilations" | awk '{ print $4 }')"
-          SUCCEEDED_DIST="$(echo "$STATS" | (grep -F "127.0.0.1:10501" || true) | awk '{ print $2 }')"
+          CACHE_HITS="$(echo "$STATS" \
+            | grep "Cache hits" | grep -v Rust | awk '{ print $3 }')"
+          FAILED_DIST="$(echo "$STATS" \
+            | grep "Failed distributed compilations" | awk '{ print $4 }')"
+          SUCCEEDED_DIST="$(echo "$STATS" \
+            | (grep -F "127.0.0.1:10501" || true) | awk '{ print $2 }')"
 
           if [ "$CACHE_HITS" -eq 0 ]; then
             2>&1 echo "No cache hits when there should be some"
@@ -230,13 +254,16 @@ jobs:
             exit 1
           fi
 
+          ### Do test user cleanup
           sccache --stop-server
           wait $SERVER_PID || true
           killall sccache-dist || true
           EOH
 
+          ### Do root user cleanup
           killall sccache-dist || true
           wait $BUILD_SERVER_PID || true
           sleep 2
-          echo "Done"
 
+          ### Finished
+          echo "Done"
